variants:
  - name: standard
    description: "base line. Just a few simple tools. For example used to work on this repo."
    steps:
      - dnf install -y bash curl jq yq openssl git tar npm && dnf clean all
      - npm install -g yaml-language-server unified-language-server vscode-langservers-extracted
    tests: []
  - name: kubectl-tools
    description: "some simple tools to work with k8s"
    steps:
      - |
        dnf install -y bash curl jq yq openssl git tar && \
        dnf clean all
      - |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
        chmod +x kubectl && \
        mkdir -p /usr/local/bin && \
        mv ./kubectl /usr/local/bin/kubectl
      - dnf install -y helm
      - npm install -g yaml-language-server unified-language-server vscode-langservers-extracted
    tests:
      - kubectl --help && helm version
  - name: dotnet-dev
    description: "for dotnet development"
    steps:
      - dnf install -y bash curl jq yq openssl git tar gzip dotnet-sdk-10.0 && dnf clean all
      - |
        curl -L -o /tmp/omnisharp-linux-x64.tar.gz  https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.15/omnisharp-linux-x64-net6.0.tar.gz  && \
        mkdir /home/pi/.omnisharp && \
        tar -xzf /tmp/omnisharp-linux-x64.tar.gz   -C /home/pi/.omnisharp  && \
        ln -s /home/pi/.omnisharp/OmniSharp /usr/local/bin/omnisharp && \
        chmod +x /usr/local/bin/omnisharp && \
        rm -rf /tmp/omnisharp-linux-x64.tar.gz
      - npm install -g yaml-language-server unified-language-server vscode-langservers-extracted  
    tests:
      - dotnet --version
