variants:
  - name: standard
    steps:
      - dnf install -y bash curl jq yq openssl git tar && dnf clean all

  - name: kubectl-tools
    steps:
      - |
        dnf install -y bash curl jq yq openssl git tar && \
        dnf clean all
      - |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
        chmod +x kubectl && \
        mkdir -p /usr/local/bin && \
        mv ./kubectl /usr/local/bin/kubectl

  - name: dotnet-dev
    steps:
      - dnf install -y bash curl jq yq openssl git tar dotnet-sdk-10.0 && dnf clean all
